### ISSUE TITLE
Current version compatible with Nova 1.3.0?

### ISSUE THREAD

**Issue by StanBarrows** [romegadigital/IE11Compatibility#1]
Hey there,

First of all thanks for the package. 

My question: Is the current version compatible with the latest nova 1.3.0?

Cheers,
Stan

**Comment by bradenkeith** [comment]
@StanBarrows It should be! If there were many style changes in the latest release, it would just be a matter of me recompiling, which I'll probably do once I update Nova in one of my projects. If you notice any particular issues with 1.3.0 feel free to report it and I'll take a look.

**Comment by StanBarrows** [comment]
Thanks for the update! I'll take a look.
