### ISSUE TITLE
Checkboxes lose styling

### ISSUE THREAD

**Issue by themuddfamily2** [romegadigital/IE11Compatibility#2]
All the checkbox lose styling - It still works but the background isn't blue like it should be so you cannot tell if its ticked or not.

![image](https://user-images.githubusercontent.com/9141378/52052569-c556fd00-254e-11e9-9404-dab9115deeb1.png)

Image above shows 1 checked checkbox and other non-checked

Can't tell the difference

**Comment by bradenkeith** [comment]
Thank you for reporting. This is due to a nova update. I just tagged an update to this package (1.0.2) which should resolve.

**Comment by themuddfamily2** [comment]
@bradenkeith Thanks so much 👍
