### ISSUE TITLE
Not yet ready for nova ~2.0

### ISSUE THREAD

**Issue by tomhatzer** [romegadigital/IE11Compatibility#5]
Just a quick link to the comment in the nova-issues repository: https://github.com/laravel/nova-issues/issues/822#issuecomment-509610744

This package is not yet ready for nova version 2.

The comment by @bradenkeith here https://github.com/laravel/nova-issues/issues/822#issuecomment-510087305 shows a basic roadmap with the "way to go".

I just tried sending the js files through babel and convert the js to es2015 compatible javascript code, but that didn't work at all as the files were too big to minify them and the process quit right afterwards.
Even changing the nova webpack config to load babel and output the files as es2015 compatible had no effects.

If anyone has any more details on this, I'd be happy to discuss it further and maybe even get a solution for this.

**Comment by tomhatzer** [comment]
I tried a few things today and was able to get rid of the first error message. You can find my progress here: https://github.com/tomhatzer/IE11Compatibility/tree/nova2

**Comment by yehudahkay** [comment]
https://github.com/romegadigital/IE11Compatibility/pull/7
